abstract: Catalyst based application
author: Florian Ragwitz,,,
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Gitweb
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7006
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  YAML: 0
version: 0.01
